trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipelines/*
    - azure-pipelines.yml
pool:
  vmImage: 'ubuntu-latest'

# extends:
#   - template: pipelines/resources.yml
#   - template: pipelines/build.yml
#   - template: pipelines/release.yml

stages:
- template: pipelines/build.yml
- template: pipelines/release.yml