trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipelines/*
    - azure-pipelines.yml
pool:
  vmImage: 'ubuntu-latest'

stages:
- template: pipeline/build.yaml
- template: pipeline/release.yaml