trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - pipelines/*
    - azure-pipelines.yml
pool:
  vmImage: 'ubuntu-latest'

stages:
- template: pipelines/build.yaml
- template: pipelines/release.yaml