# Explicitly set none for repositry trigger
# trigger:
# - none

# resources:
#   pipelines:
#   - pipeline: myappbuild  # Name of the pipeline resource
#     source: build-artifact-pipeline # Name of the triggering pipeline
#     trigger: 
#       branches:
#       - main

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: DevDeploy
    pool: 
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:          
          # - download: myappbuild
          #   artifact: drop  
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(System.ArtifactsDirectory)'
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '**/*.zip'
              destinationFolder: '$(agent.builddirectory)'
              cleanDestinationFolder: false
          - script: |  
              ls -R $(agent.builddirectory)