# Explicitly set none for repositry trigger
# trigger:
# - none

resources:
  pipelines:
  - pipeline: myappbuild  # Name of the pipeline resource
    source: build-artifact-pipeline # Name of the triggering pipeline
    trigger: 
      branches:
      - main

stages:
- stage: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: DevDeploy
    pool: 
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:          
          - download: myappbuild
            artifact: drop  
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(PIPELINE.WORKSPACE)/myappbuild/drop/$(resources.pipeline.myappbuild.runID).zip'
              destinationFolder: '$(agent.builddirectory)'
              cleanDestinationFolder: false
          - script: |  
              cat $(agent.builddirectory)/greatcode.txt