parameters:
  - name: buildId
    type: string
    default: 
  - name: artifactName
    type: string
    default:
  - name: pipelineName
    type: string
    default:
  - name: runID
    type: string
    default:
  - name: vmImageName
    type: string
    default:

steps:
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: ${{ parameters.runID }}
      destinationFolder: '$(agent.builddirectory)'
      cleanDestinationFolder: false
  - script: |  
      cat $(agent.builddirectory)/greatcode.txt